#
# This file is part of ***  M y C o R e  ***
# See http://www.mycore.de/ for details.
#
# MyCoRe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MyCoRe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MyCoRe.  If not, see <http://www.gnu.org/licenses/>.
#

# $Revision$ : $Date$

# name of project - laade
MCR.NameOfProject=laade
MIR.projectid.default=laade
MCR.CLI.Classes.External=%MCR.CLI.Classes.External%,org.mycore.mir.laade.MIRLaadeImport


# supported languages
MCR.Metadata.Languages=de,en
# Layout
MIR.CustomLayout.JS=laade.js
MIR.CustomLayout.CSS=laade.css




MCR.IIIFImage.thumbnail.Derivate.Types=derivate_types:cover

##############################################################################
#                                                                            #
# reset new Metadata Layout                                                  #
#                                                                            #
##############################################################################
MCR.ContentTransformer.mycoreobject-modsmeta.Stylesheet=%MCR.ContentTransformer.mycoreobject-rights.Stylesheet%,xsl/metadata/mods-metadata.xsl
MCR.ContentTransformer.mycoreobject-saxon.Stylesheet=%MCR.ContentTransformer.mycoreobject-modsmeta.Stylesheet%,xsl/metadata/mods-metadata-page.xsl
MCR.ContentTransformer.mycoreobject-saxon.TransformerFactoryClass=net.sf.saxon.TransformerFactoryImpl

# Use Saxon pipeline for metadata objects
MCR.ContentTransformer.response-browse-saxon.Stylesheet=xsl/response2mycoreobject.xsl,%MCR.ContentTransformer.mycoreobject-saxon.Stylesheet%
MCR.ContentTransformer.response-browse-saxon.TransformerFactoryClass=net.sf.saxon.TransformerFactoryImpl

MCR.Jersey.Resource.Packages=%MCR.Jersey.Resource.Packages%,org.mycore.wavesurfer.prerender.resources

MCR.Wavesurfer.MimeType=audio/mpeg,audio/mp3,audio/wav,audio/x-midi,audio/mp4,audio/ogg
